// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOGkPY5CbOcp3f5VJRUUeSyARd8Gus4n8',
    appId: '1:938786366050:web:4f5dadc8c59e344709e73b',
    messagingSenderId: '938786366050',
    projectId: 'muscu-759fb',
    authDomain: 'muscu-759fb.firebaseapp.com',
    storageBucket: 'muscu-759fb.appspot.com',
    measurementId: 'G-HL3FSSJC0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYcKyC0qtXgOFIInab-s_I2YSJukgJ5JA',
    appId: '1:938786366050:android:fff170a9a63013cc09e73b',
    messagingSenderId: '938786366050',
    projectId: 'muscu-759fb',
    storageBucket: 'muscu-759fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC4M-vZz6qqi5ZdbMylYHn_vT0NafvZGA',
    appId: '1:938786366050:ios:a657b1585edec55a09e73b',
    messagingSenderId: '938786366050',
    projectId: 'muscu-759fb',
    storageBucket: 'muscu-759fb.appspot.com',
    iosClientId: '938786366050-gdet7qpt4pr0gpaj2fl419vl0dpn2jv5.apps.googleusercontent.com',
    iosBundleId: 'com.example.muscuappwithfire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC4M-vZz6qqi5ZdbMylYHn_vT0NafvZGA',
    appId: '1:938786366050:ios:a657b1585edec55a09e73b',
    messagingSenderId: '938786366050',
    projectId: 'muscu-759fb',
    storageBucket: 'muscu-759fb.appspot.com',
    iosClientId: '938786366050-gdet7qpt4pr0gpaj2fl419vl0dpn2jv5.apps.googleusercontent.com',
    iosBundleId: 'com.example.muscuappwithfire',
  );
}
